services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/apps/web
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: bun run dev


  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/apps/server
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - apps/server/.env.development
    ports:
      - "4000:4000"
    command: bun run dev

