// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzscnckjhxzjeowjqywa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6c2NuY2tqaHh6amVvd2pxeXdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MjcyOTAsImV4cCI6MjA3MDQwMzI5MH0.dW8LXC2kMhzaCn99c3vkmEgxA_59vRQfRceCzXLFjbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});